
from pathlib import Path

PROJECT = {
    "docs": [
        "agents",
        "business_knowledge",
        "business_rules",
        "workflows",
        "architecture",
        "api",
        "database"
    ],
    "database": [
        "schema",
        "seed",
        "migrations",
        "views",
        "procedures",
        "functions"
    ],
    "backend": [
        "api",
        "services",
        "models",
        "repositories",
        "middleware"
    ],
    "frontend": [
        "web",
        "admin"
    ],
    "ai": [
        "agents",
        "prompts",
        "memory",
        "workflows"
    ],
    "tools": [
        "project_generator",
        "scripts"
    ]
}

SQL_FILES = [
    "companies.sql",
    "users.sql",
    "roles.sql",
    "permissions.sql",
    "user_roles.sql",
    "warehouses.sql",
    "products.sql",
    "customers.sql",
    "suppliers.sql",
    "purchase_orders.sql",
    "purchase_order_items.sql",
    "sales_orders.sql",
    "sales_order_items.sql",
    "inventory.sql",
    "stock_movements.sql",
    "price_lists.sql",
    "invoices.sql",
    "payments.sql",
    "expenses.sql",
    "financial_years.sql"
]

def readme(path):
    (path / "README.md").write_text(
        f"# {path.name}\n\nGenerated by ATM OS Project Generator\n",
        encoding="utf-8"
    )

root = Path(".")

for parent, children in PROJECT.items():
    p = root / parent
    p.mkdir(parents=True, exist_ok=True)
    readme(p)

    for child in children:
        c = p / child
        c.mkdir(parents=True, exist_ok=True)
        readme(c)

schema = root / "database" / "schema"

for sql in SQL_FILES:
    (schema / sql).write_text(
        f"-- {sql}\n",
        encoding="utf-8"
    )

print("===================================")
print("ATM OS Structure Generated")
print("Folders :", sum(len(v) for v in PROJECT.values()))
print("SQL Files:", len(SQL_FILES))
print("Done.")
print("===================================")
